[build]
  command = "npm run build"
  # Publish directory set to .next to override UI setting
  # @netlify/plugin-nextjs will handle the actual deployment
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

